### ISSUE TITLE
TMS-54 Code Review on Backend changes

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#13]
TMS-54 Code Review comments on the Backend changes

@Thejaswini5798   as discussed and reviewed the code together, we must do the following.
1. Remove the Tmsmaven1/App. java and AppTest.java - as it was created on the command line maven project. 
2. The Employee BO was renamed from Employee.java to `EmployeeBO.java` last week to be consistent with any BO. Hence the changes made in `Employee.java` was not required and also we should remove the entire class from the package - `Employee.java`.
3. In the EmployeeCreateServlet.java, a good job done was to overload the methods 'setField()` and 'validate()` with an integer value, from the existing one that deals with the String value. However the validate method was NOT invoked in the doPost() method right after we obtain the value from request.getParameter(). 

Commit Ref : https://github.com/raghsonlinedotcom/mini-project-tms/commit/27d00f9095015247e26f04973cc5b86888b00a1f

**Comment by Thejaswini5798** [comment]
Review comments were incorporated and the changes were pushed into the feature/view-edit-member branch. Please refer to the commit id :"be8c55417925315ce8668a9c24bf5c404d0dfdc0" to find the changes.
