### ISSUE TITLE
TMS-39 Login UI - Review Comments

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#14]
TMS-39 Login UI Review Comments

@Thejaswini5798   As discussed and reviewed together, here are the comments and action items.

1. Formatting should be done for all the changes. 
2. Remove the attribute - aria-describedby="pwdPattern" in the `login.jsp` page as it does not add any value. 
3. Good thing you had added the header separately on the login.jsp as we don't need the menu. However you forgot to add/include the sticky footer css after the style.css in the `login.jsp` page. 

Commit Ref # : https://github.com/raghsonlinedotcom/mini-project-tms/commit/5ae131caef457ba819452d62dad212e9e78c28e1

**Comment by Thejaswini5798** [comment]
Formatting and removeing the  attribute - aria-describedby="pwdPattern" in the login.jsp changes were done and pushed into the feature/view-edit-member branch. Please refer to the 
commit id :"be8c55417925315ce8668a9c24bf5c404d0dfdc0" to find the changes.
