### ISSUE TITLE
TMS-38 Login Backend - Review Comments

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#15]
TMS-38 Login Backend - Review Comments

@SairamVemulapalli96   As discussed and reviewed together, here are the action items

1. LoginServlet.java - doGet() should be removed
2. LoginServlet.java - the messages in the catch block is missing. Only a conditional printStackTrace() is present, which is insufficient. 
3. LoginDAO - write a new method named verifyUser(int, String) that takes the empId, and password as arguments, and write the implementation that verifies an User with the matching UserId and Password. Modify the LoginServlet doPost() accordingly.
4. UnitTest - method stands obsolete as the testing was not done on the login at all, as it just gets the employee by empId, which is a duplicate of getEmployeeById(). Modify it accordingly.

Commit Ref # : https://github.com/raghsonlinedotcom/mini-project-tms/commit/9f7a8336f7cb99a4199ffdf23e3b2eb2a9ce1609

**Comment by SairamVemulapalli96** [comment]
Review comments were incorporated and the changes were pushed into the feature/view-edit-member branch. Please refer to the commit id "e9bd1e489a1065ac147b435bb943dd585fdd2ee9" to find the changes. 
![TMS - 38 Login Backend Review comments incoroprated](https://user-images.githubusercontent.com/119736781/209903737-825b8cc4-da19-4357-b84e-cd13041f7c63.JPG)
