### ISSUE TITLE
Wrong URL Path for list.jsp for Employees

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#17]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/8794d8dad0e961f86871838fa42963f327c15f97/src/main/java/com/tutorials/tms/web/EmployeeListServlet.java#L57

@Arunprasad137  the URL to the JSP should reflect the right folder structure. Guess you missed to pay attention.
Present : "list.jsp"
Expected : "/member/list.jsp" as we have moved all the employee related .jsp files into a folder named "/member".

**Comment by SairamVemulapalli96** [comment]
Fixed it myself sir @itsraghz . Please refer to the commit id "eefccac586a801c963aeb63a3ac60f105d3ed460" for the changes. Thank you

**Comment by itsraghz** [comment]
Thank you @SairamVemulapalli96 . @Arunprasad137  FYI.
