### ISSUE TITLE
Inappropriate placement of list.jsp as a separate menu

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#18]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/8794d8dad0e961f86871838fa42963f327c15f97/src/main/webapp/inc/menu.jsp#L31

@SairamVemulapalli96  The `list.jsp` to display "View All Employees" can better be placed under the "Employee" menu for the right logical grouping.  Please fix this.

**Comment by SairamVemulapalli96** [comment]
Hi @itsraghz sir, changes were made accordingly. Please refer to the commit id "ad8d5e1f98138880eee75e4e7ae0e6ec673a2fda" for the changes. Thank you, sir.
