### ISSUE TITLE
InActive Managers Are Displaying in the List of All Managers.

### ISSUE THREAD

**Issue by Arunprasad137** [raghsonlinedotcom/mini-project-tms#21]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/554b3545618d703eb2219bfad93290a856150b9c/src/main/webapp/create.jsp#L314

InActive Managers Are Displaying in the List of All Managers.
Please once check It.

**Comment by itsraghz** [comment]
A good catch @Arunprasad137 ! Keep it up.

**Comment by itsraghz** [comment]
@Arunprasad137  you can also raise a Jira Issue in Sprint 6.. if @SairamVemulapalli96  can fix this quickly we can make it in Sprint 5 itself, else better to take it in Sprint 6 - Manager, Audit Trial as this does not have an urgency.

**Comment by SairamVemulapalli96** [comment]
Thanks @Arunprasad137 for the information. Sir @itsraghz I have fixed the issue as part of the sprint - 5 itself.

**Comment by itsraghz** [comment]
Great,. thanks @SairamVemulapalli96 . If @Arunprasad137  has pushed all his items, then we can do the deployment of Sprint 5 today itself at the earliest, with which we can close the sprint and also merge the feature branch to main.
