### ISSUE TITLE
Default value is broken for the BloodGroup in Creation with AppDev Mode

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#24]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/523c2aac70adf79962284acb05daea70428a6c5c/src/main/webapp/create.jsp#L240

Default value is broken for the BloodGroup in Creation with AppDev Mode

**Comment by Arunprasad137** [comment]
The Issue was fixed :)
