### ISSUE TITLE
Password should not be printed in the log as it is sensitive

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#27]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/440850f4279412a067300dce76d8953a6099788c/src/main/java/com/raghsonline/miniprojects/tms/dao/EmployeeDAOImpl.java#L287

Password should not be printed as it is a sensitive info.

**Comment by SairamVemulapalli96** [comment]
Thanks @itsraghz sir. The issue is fixed now in the commit with id "92b48499feeda4b16ddd8b5e2557472a3afd4d35"
