### ISSUE TITLE
There is an Error In that line (UPDATEDBY)

### ISSUE THREAD

**Issue by Arunprasad137** [raghsonlinedotcom/mini-project-tms#28]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/440850f4279412a067300dce76d8953a6099788c/src/main/java/com/raghsonline/miniprojects/tms/dao/EmployeeDAOImpl.java#L246

There is an Error In that line (UPDATEDBY). It should be UPDATED_BY

**Comment by SairamVemulapalli96** [comment]
Thanks @Arunprasad137 . Issue is fixed in the commit with id "92b48499feeda4b16ddd8b5e2557472a3afd4d35".
