### ISSUE TITLE
The @DisplayName should not have a running set of characters 

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#29]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/440850f4279412a067300dce76d8953a6099788c/src/test/java/com/raghsonline/miniprojects/tms/junit/EmployeeDAOTest.java#L309

The @DisplayName should not have a running set of characters , as it is not a best practice. Kindly remove it in all the other occurrences.

**Comment by Arunprasad137** [comment]
Issue Resolved.
Thank you.
