### ISSUE TITLE
Not Setting the "IsActive".

### ISSUE THREAD

**Issue by Arunprasad137** [raghsonlinedotcom/mini-project-tms#30]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/ad91ea9822718e13ef91209ffe71b6bffc60656a/src/main/java/com/raghsonline/miniprojects/tms/dao/EmployeeDAOImpl.java#L242

Not Setting the "IsActive".
Please set that one.

**Comment by SairamVemulapalli96** [comment]
Issue resolved. Thanks @Arunprasad137 .
