### ISSUE TITLE
Mandatory Asterisk is missing for Member

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#32]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/1935f67aa55721f0c37c775dafd0d154897180d2/src/main/webapp/member/edit.jsp#L97

Mandatory Asterisk is missing for Member

**Comment by KarthiikHKiran** [comment]
TMS-143 Mandatory Asterisk Bug is fixed and pushed into remote feature/leave-request branch. Please refer to the
commit ID:-3959ea4cec5d1a4daa90c455bb21639c2f63fb0c
