### ISSUE TITLE
Mandatory Asterisk is missing Manager Edit Member Page

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#33]
https://github.com/raghsonlinedotcom/mini-project-tms/blob/1935f67aa55721f0c37c775dafd0d154897180d2/src/main/webapp/manager/managereditmember.jsp#L96

Mandatory Asterisk is missing Manager Edit Member Page

**Comment by Arunprasad137** [comment]
Fixed the issue.
