### ISSUE TITLE
Updated By is show as zero instead of null in View Leave

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#39]
Upon successfully saving the leave details, the http://localhost:18080/tmsmaven/CreateLeaveDetails page returns to a JSP page where we show the leave details of an employee with the value 0 for the column "Updated By". Ideally it is just created and the Updated By should be blank in the UI page, as it is stored as NULL in the database.

**Comment by Thejaswini5798** [comment]
TMS-157 JSP page where we show the leave details of an employee with the value 0 for the column "Updated By". The updated by should be blank in the UI page this bug as been fixed.
Please refer to the commit id : ff71d7f49ed460cdbe1f584203d8aa44090e865d
